# Site settings
title: Jekyll Theme - Lazy
email: genadimihaylov@gmail.com
description:
  This is a very minimalistic and beautiful theme for jekyll.
destination: 'docs'
exclude: [_assets, Gemfile, Gemfile.lock, gulpfile.js, package.json, package-lock.json, npm-debug.log, README.md, node_modules]
# baseurl: "" # the sub-path of your site, e.g. /blog
baseurl: '/Lazy'
url: "" # the base hostname & protocol for your site, e.g. http://example.com

twitter_username: jekyllrb
github_username:  genadi60

# Build settings
markdown: kramdown
# theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
